version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: zalogram-backend
    working_dir: /app
    command: sh scripts/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - backend-node-modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - dynamodb
      - redis
      - kafka
      - elasticsearch
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:29092
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true
    networks:
      - zalogram-network

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: zalogram-dynamodb
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    volumes:
      - dynamodb-data:/home/dynamodblocal
    networks:
      - zalogram-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: zalogram-dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb
    networks:
      - zalogram-network

  redis:
    image: redis:7-alpine
    container_name: zalogram-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - zalogram-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zalogram-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - zalogram-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: zalogram-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - zalogram-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: zalogram-elasticsearch
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - zalogram-network

volumes:
  backend-node-modules:
  dynamodb-data:
  redis-data:
  es-data:

networks:
  zalogram-network:
    driver: bridge
